# Generated by Django 5.2.11 on 2026-03-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_is_online_customuser_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_seen',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
